package it.polimi.ingsw.am55.network.command;


import it.polimi.ingsw.am55.network.server.ServerApplication;
import it.polimi.ingsw.am55.virtualview.VirtualView;

/**
 * Command used by a newly connected client to register its temporary lobby session.
 */
public class RegisterLobbyCommand implements ServerCommand {

    /**
     * Serialization identifier used when this command crosses RMI or socket object streams.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Temporary session id generated by the client before it creates or joins a game.
     */
    private final String sessionId;

    /**
     * Creates a lobby-registration command.
     *
     * @param sessionId temporary session identifier generated by the client
     */
    public RegisterLobbyCommand(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * Requires locking because lobby registration changes shared server state.
     *
     * @return always {@code true}
     */
    @Override
    public boolean requiresLock() {
        return true;
    }

    /**
     * Registers the sender in the server lobby.
     *
     * @param serverApplication server-side application receiving the command
     * @param sender            client endpoint to register
     * @throws Exception if registration or initial message delivery fails
     */
    @Override
    public void execute(ServerApplication serverApplication, VirtualView sender) throws Exception {
        serverApplication.registerLobbyClient(sessionId, sender);
    }
}