package it.polimi.ingsw.am55.network;

import it.polimi.ingsw.am55.ClientModel.ClientModel;
import it.polimi.ingsw.am55.ClientModel.ClientModelUpdater;
import it.polimi.ingsw.am55.message.MessageToClient;
import it.polimi.ingsw.am55.network.ClientConnectionControl;
import it.polimi.ingsw.am55.network.command.PingCommand;
import it.polimi.ingsw.am55.network.command.RegisterLobbyCommand;
import it.polimi.ingsw.am55.network.command.ServerCommand;
import it.polimi.ingsw.am55.virtualview.VirtualServer;
import it.polimi.ingsw.am55.virtualview.VirtualView;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.Timer;
import java.util.TimerTask;
import java.util.UUID;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * Client-side remote endpoint used by both RMI and socket transports.
 * The class implements {@link VirtualView} so the server can send callbacks to
 * the client, and {@link ClientConnectionControl} so technical messages can start
 * or stop heartbeat-related behavior. Outgoing requests are represented as
 * {@link ServerCommand} instances and are forwarded to the configured
 * {@link VirtualServer} abstraction.
 */
public class ClientImpl extends UnicastRemoteObject implements VirtualView, ClientConnectionControl {

    /**
     * Serialization identifier for the exported RMI client endpoint.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Delay, in milliseconds, between heartbeat commands sent by the client.
     */
    private static final long PING_INTERVAL_MS = 1500;
    /**
     * Maximum time, in milliseconds, that the client waits without receiving a pong before closing the connection.
     */
    private static final long SERVER_TIMEOUT_MS = 8000;

    /**
     * Server used to send commands.
     *
     * For RMI connections this is the remote server; for socket connections it is a local {@code ServerStub}.
     */
    private final VirtualServer server;
    /**
     * Client-side model updated by messages received from the server.
     */
    private final ClientModelUpdater model;
    /**
     * Temporary session identifier generated by the client while it is registered in the lobby.
     *
     * The server uses this value before a permanent player id is assigned.
     */
    private final String sessionId;

    /**
     * Permanent player identifier assigned after a successful create-game or join-game operation.
     *
     * The value is volatile because it can be read by UI code, timer tasks, and network callbacks.
     */
    private volatile String playerId;

    /**
     * Synchronization monitor that protects heartbeat state shared by timer tasks and message callbacks to store
     * the instant of pong from server.
     */
    private final Object pingLock;
    /**
     * Timestamp, in epoch milliseconds, of the latest pong received from the server.
     */
    private long lastPingFromServer;

    /**
     * Timer responsible for periodically sending {@code PingCommand} instances to the server.
     */
    private Timer pingTimer;
    /**
     * Timer responsible for detecting server-side silence from missing pong responses.
     */
    private  Timer aliveCheckerTimer;

    private ExecutorService rmiExecutor;
    /**
     * Flag that prevents multiple client heartbeat timers from being started.
     */
    private volatile boolean pingStarted;

    /**
     * Creates a client endpoint connected to the given server.
     * Generates ID for lobby client
     *
     * @param server represents a generic server used to send commands
     * @param model  local model updated when messages are received from the server
     * @throws RemoteException if the client object cannot be exported for RMI callbacks
     */
    public ClientImpl(VirtualServer server, ClientModel model) throws RemoteException {
        super();

        this.server = server;
        this.model = model;
        this.sessionId = UUID.randomUUID().toString();

        this.playerId = null;

        this.pingLock = new Object();
        this.lastPingFromServer = System.currentTimeMillis();

        this.pingTimer = new Timer(true);

        this.aliveCheckerTimer = new Timer(true);
        this.rmiExecutor = Executors.newCachedThreadPool();
        this.pingStarted = false;
    }

    /**
     * Returns the temporary session identifier used while the client is in the lobby.
     *
     * @return the generated lobby session identifier
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * Registers this client in the server lobby before a player identifier is assigned.
     *
     * @throws RemoteException if the registration command cannot be sent
     */
    public void connect() throws RemoteException {
        sendCommand(new RegisterLobbyCommand(sessionId));
    }

    /**
     * Sends a command to the server through the configured transport abstraction.
     *
     * @param command command to execute on the server application
     * @throws RemoteException if the command cannot be delivered
     */
    public void sendCommand(ServerCommand command) throws RemoteException {
        server.receiveCommand(command, this);
    }

    /**
     * Receives a server-to-client message, updates the model when required.
     * It can execute any technical network action attached to the message.
     *
     * @param message message sent by the server
     * @throws RemoteException if the callback fails at transport level
     */
    @Override
    public void onMessage(MessageToClient message) throws RemoteException {
        rmiExecutor.submit(()->executeUpdate(message));
    }

    public void executeUpdate(MessageToClient message){
        try {
            if (message.shouldUpdateModel()) {
                synchronized (model) {
                    model.handleUpdate(message);
                }
            }
            message.executeClientNetworkAction(this);

        } catch (Exception e) {
            System.out.println("[CLIENT_IMPL] Error handle message: " + e.getMessage());
        }
    }

    /**
     * Returns the player identifier associated with this client after join/create succeeds.
     *
     * @return the player identifier, or {@code null} while the client is still in the lobby
     * @throws RemoteException if the value cannot be read through the remote interface
     */
    @Override
    public String getPlayerId() throws RemoteException {
        return playerId;
    }

    /**
     * Sets the player identifier assigned by the server after connection setup succeeds.
     *
     * @param playerId player identifier associated with this client
     * @throws RemoteException if the value cannot be set through the remote interface
     */
    @Override
    public void setPlayerId(String playerId) throws RemoteException {
        this.playerId = playerId;
    }

    /**
     * Starts the heartbeat loop that periodically sends {@link PingCommand} instances
     * to the server and starts the local server availability checker.
     */
    @Override
    public void startPing() {
        if (pingStarted) return;
        pingStarted = true;
        startAliveChecker();
        pingTimer.schedule(new TimerTask() {
            /**
             * Sends one heartbeat command to the server.
             */
            @Override
            public void run() {
                try {
                    sendCommand(new PingCommand());
                } catch (Exception e) {}
            }
        }, 0, PING_INTERVAL_MS);
    }

    /**
     * Starts the local timer that closes the client when the server stops answering pings.
     */
    private void startAliveChecker() {
        aliveCheckerTimer.schedule(new TimerTask() {
            /**
             * Sends one heartbeat command to the server.
             */
            @Override
            public void run() {
                long elapsed;

                synchronized (pingLock) {
                    elapsed = System.currentTimeMillis() - lastPingFromServer;
                }

                if (elapsed > SERVER_TIMEOUT_MS) {
                    System.out.println("[CLIENT_IMPL] Server unreachable (either server down or client down): I close the client.");
                    closeConnection();
                }
            }
        }, PING_INTERVAL_MS, PING_INTERVAL_MS);
    }

    /**
     * Stops the heartbeat and server availability timers.
     */
    @Override
    public void stopPing() {
        pingStarted = false;
        try {
            pingTimer.cancel();
        } catch (Exception ignored) {
        }

        try {
            aliveCheckerTimer.cancel();
        } catch (Exception ignored) {
        }
    }

    /**
     * Updates the timestamp of the last pong received from the server.
     */
    @Override
    public void pongFromSever() {
        synchronized (pingLock) {
            lastPingFromServer = System.currentTimeMillis();
        }
    }

    /**
     * Stops network timers, closes the server-side abstraction when possible, and
     * terminates the client process asynchronously.
     */
    @Override
    public void closeConnection() {
            System.out.println("[CLIENT_IMPL] Client ping stopped");
            try{
                server.close();
            }catch(Exception e){}
            System.out.println("[CLIENT_IMPL] I close the client.");
            System.exit(0);

    }

    /**
     * Closes this remote client endpoint.
     * The current implementation keeps the method available for the remote
     * contract but performs no local cleanup. Connection cleanup is handled by
     * {@link #closeConnection()} when the client must terminate.
     *
     * @throws RemoteException if the remote close callback fails
     */
    @Override
    public void close() throws RemoteException {}

}