package it.polimi.ingsw.am55.network;

import it.polimi.ingsw.am55.controller.GameController;
import it.polimi.ingsw.am55.message.LobbyStatusMessage;
import it.polimi.ingsw.am55.message.MessageDelivery;
import it.polimi.ingsw.am55.message.MessageToClient;
import it.polimi.ingsw.am55.message.PongMessage;
import it.polimi.ingsw.am55.message.QuitLobbyMessage;
import it.polimi.ingsw.am55.message.StartPingMessage;
import it.polimi.ingsw.am55.network.command.ServerCommand;
import it.polimi.ingsw.am55.virtualview.VirtualServer;
import it.polimi.ingsw.am55.virtualview.VirtualView;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Central server-side network façade shared by RMI and socket transports.
 *
 * The class receives client commands, delegates game logic to {@link GameController},
 * tracks lobby and game clients, delivers messages through {@link MessageDelivery},
 * and monitors client availability with a heartbeat mechanism.
 */
public class ServerApplication extends UnicastRemoteObject implements VirtualServer, MessageDelivery {

    /**
     * Serialization identifier for the exported RMI server application.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Maximum time, in milliseconds, that the server allows between two pings from the same client.
     */
    private static final long PING_TIMEOUT_MS = 6_000;

    /**
     * Controller used to execute game operations requested through network commands.
     */
    private final GameController controller;

    /**
     * Registered clients that are in game.
     *
     * The key is the permanent player id; the value is the callback endpoint used to deliver messages to that player.
     */
    private final Map<String, VirtualView> gameClients;
    /**
     * Connected clients that are still waiting in the lobby.
     *
     * The key is the temporary session id generated by the client; the value is the callback endpoint used before the player id exists.
     */
    private final Map<String, VirtualView> lobbyClients;
    /**
     * Heartbeat registry for both lobby and game clients.
     *
     * Each entry stores a client endpoint and the epoch-millisecond timestamp of the latest ping received from it.
     */
    private final Map<VirtualView, Long> lastPingByClient;
    /**
     * Crash-state guard used to ensure that a disconnected game client triggers the game-crash flow only once.
     */
    private AtomicBoolean isGameCrashed;
    /**
     * Synchronization monitor used for commands that mutate shared game or connection state.
     */
    private final Object gameLock = new Object();

    /**
     * Executor that runs incoming RMI commands outside the RMI dispatch thread, in this way RMI became asynchronous
     */
    private final ExecutorService rmiExecutor;
    /**
     * Single-thread executor that serializes heartbeat timeout and disconnection handling.
     */
    private final ExecutorService disconnectionExecutor;

    /**
     * Timer that periodically scans client heartbeat timestamps for timeouts.
     */
    private Timer aliveChecker;
    /**
     * Flag that prevents multiple server heartbeat checkers from being scheduled at the same time.
     */
    private volatile boolean aliveCheckerStarted;

    /**
     * Creates the exported server application and initializes client registries,
     * heartbeat state, and command executors.
     *
     * @throws RemoteException if the server object cannot be exported for RMI
     */
    public ServerApplication() throws RemoteException {
        super();

        this.controller = new GameController();

        this.lobbyClients = new HashMap<>();
        this.gameClients = new HashMap<>();
        this.lastPingByClient = new HashMap<>();

        this.aliveChecker = new Timer(true);
        this.aliveCheckerStarted = false;
        this.isGameCrashed = new AtomicBoolean(false);
        this.rmiExecutor = Executors.newCachedThreadPool();
        this.disconnectionExecutor = Executors.newSingleThreadExecutor();
        System.out.println("[SERVER_APP] ServerApplication created.");
    }


    /**
     * Receives a command through RMI and schedules its execution asynchronously.
     *
     * Socket clients do not enter through this method: their skeleton reads commands
     * from the object stream and invokes {@link #executeCommand(ServerCommand, VirtualView)} directly.
     *
     * @param command command requested by the client
     * @param sender  remote callback endpoint of the client that sent the command
     * @throws RemoteException if the RMI call fails before scheduling the command
     */
    @Override
    public void receiveCommand(ServerCommand command, VirtualView sender) throws RemoteException {
        rmiExecutor.submit(() -> {
            try {
                executeCommand(command, sender);
            } catch (Exception e) {
                System.out.println("[SERVER_APP] Error while executing command from RMI: " + e.getMessage());
                e.printStackTrace();
            }
        });
    }

    /**
     * Closes the remote server abstraction.
     *
     * The current implementation keeps the method available for transport symmetry;
     * server shutdown is handled outside this remote callback.
     *
     * @throws RemoteException if the remote close callback fails
     */
    @Override
    public void close() throws RemoteException {
    }

    /**
     * Executes a client command using the locking policy declared by the command itself.
     *
     * @param command command to execute
     * @param sender  client endpoint that sent the command
     * @throws Exception if command execution fails
     */
    public void executeCommand(ServerCommand command, VirtualView sender) throws Exception {
        System.out.println("[SERVER_APP] Command execution: "
                + command.getClass().getSimpleName()
                + ", sender = "
                + (sender == null ? "null" : sender.getClass().getSimpleName()));

        if (command.requiresLock()) {
            synchronized (gameLock) {
                command.execute(this, sender);
            }
        } else {
            command.execute(this, sender);
        }

        System.out.println("[SERVER_APP] Command completed: "
                + command.getClass().getSimpleName());
    }

    /**
     * Registers a newly connected client in the lobby and starts heartbeat monitoring.
     *
     * @param sessionId temporary lobby session identifier generated by the client
     * @param client    client callback endpoint
     * @throws Exception if the initial technical message cannot be delivered
     */
    public void registerLobbyClient(String sessionId, VirtualView client) throws Exception {
        if (sessionId == null || client == null) {
            System.out.println("[SERVER_APP] RegisterLobbyClient ignored: sessionId/client null.");
            return;
        }

        synchronized (lobbyClients) {
            lobbyClients.put(sessionId, client);
        }

        synchronized (lastPingByClient) {
            lastPingByClient.put(client, System.currentTimeMillis());
        }
        sendToSession(sessionId, new StartPingMessage());

        sendToSession(
                sessionId,
                new LobbyStatusMessage(
                        controller.getLobbyView(),
                        "Stato lobby sincronizzato."
                )
        );

        startAliveChecker();

        System.out.println("[SERVER_APP] Client registered in lobby. SessionId =" + sessionId);
    }
    /**
     * Removes a client from the lobby registry and closes its callback endpoint.
     *
     * @param sessionId lobby session identifier to remove
     */
    private void unregisterLobbyClient(String sessionId) {
        if(sessionId==null){
            System.out.println("[SERVER_APP] unregisterLobbyClient ignored: sessionId is null.");
            return;
        }

        VirtualView sender;
        synchronized (lobbyClients) {
            sender = lobbyClients.get(sessionId);
            lobbyClients.remove(sessionId);
        }

        synchronized (lastPingByClient) {
            if (sender != null) {
                lastPingByClient.remove(sender);
            }
            System.out.println("[SERVER_APP] Disconnected clients in lastPingByClient: " + lastPingByClient);
            if(lastPingByClient.isEmpty()) {
                stopAliveChecker();
            }
        }
        if (sender != null) {
            try {
                sender.close();
            } catch (Exception ignored) {
            }
        }
        System.out.println("[SERVER_APP] Client removed from lobby. SessionId = " + sessionId);
    }
    /**
     * Creates a game through the controller and completes the network registration if successful.
     *
     * @param playerId   player identifier chosen by the client
     * @param totemColor selected totem color
     * @param numPlayers requested number of players
     * @param sessionId  temporary lobby session identifier
     * @throws Exception if controller execution or message delivery fails
     */
    public void createGame(String playerId, String totemColor, int numPlayers, String sessionId) throws Exception {
        MessageToClient message =
                controller.createGame(playerId, totemColor, numPlayers);

        completeConnectionSetup(playerId, sessionId, message);
    }

    /**
     * Joins an existing game through the controller and completes the network registration if successful.
     *
     * @param playerId   player identifier chosen by the client
     * @param totemColor selected totem color
     * @param sessionId  temporary lobby session identifier
     * @throws Exception if controller execution or message delivery fails
     */
    public void joinGame(String playerId, String totemColor, String sessionId) throws Exception {
        MessageToClient message =
                controller.joinGame(playerId, totemColor);

        completeConnectionSetup(playerId, sessionId, message);
    }

    /**
     * Moves a client from the lobby registry to the game registry when create/join succeeds.
     *
     * @param playerId  permanent player identifier assigned to the client
     * @param sessionId temporary lobby session identifier
     * @param message   controller response that decides whether setup succeeded
     * @throws Exception if the client endpoint cannot be updated or the response cannot be delivered
     */
    private void completeConnectionSetup(String playerId, String sessionId, MessageToClient message) throws Exception {
        VirtualView client;

        synchronized (gameLock) {
            client = lobbyClients.get(sessionId);

            if (client == null) {
                System.out.println("[SERVER_APP] Lobby session not found: " + sessionId);
                return;
            }

            if (!message.isConnectionSetupSuccessful()) {
                sendToSession(sessionId, message);
                return;
            }

            lobbyClients.remove(sessionId);
            client.setPlayerId(playerId);
            gameClients.put(playerId, client);
        }

        System.out.println("[SERVER_APP] Client moved from lobby to game: " + playerId);

        message.deliver(playerId, this);
        broadcastLobbyStatus();
    }

    /**
     * Applies a totem placement request and delivers the resulting game update.
     *
     * @param playerId player requesting the action
     * @param index    target position on the trail
     */
    public void placeTotem(String playerId, int index){
        System.out.println("[SERVER_APP] placeTotem called by: "
                + playerId
                + ", index = "
                + index);

        MessageToClient message = controller.placeTotem(playerId, index);

        System.out.println("[SERVER_APP] placeTotem produced message: "
                + message.getClass().getSimpleName());

        message.deliver(playerId, this);
    }

    /**
     * Applies a card-pick request and broadcasts the resulting game update.
     *
     * @param playerId player requesting the action
     * @param cardId   identifier of the selected card
     */
    public void pickCard(String playerId, int cardId){
        System.out.println("[SERVER_APP] pickCard called by: "
                + playerId
                + ", cardId = "
                + cardId);

        MessageToClient message = controller.pickCard(playerId, cardId);

        System.out.println("[SERVER_APP] pickCard produced message: "
                + message.getClass().getSimpleName());

        message.deliver(playerId, this);
    }

    /**
     * Applies a special-card pick request and broadcasts the resulting game update.
     *
     * @param playerId player requesting the action
     * @param cardId   identifier of the selected special card
     */
    public void pickSpecial(String playerId, int cardId){
        System.out.println("[SERVER_APP] pickSpecial called by: "
                + playerId
                + ", cardId = "
                + cardId);

        MessageToClient message = controller.pickSpecial(playerId, cardId);

        System.out.println("[SERVER_APP] pickSpecial produced message: "
                + message.getClass().getSimpleName());

        message.deliver(playerId, this);
    }

    /**
     * Handles a voluntary game quit, notifies game and lobby clients, and resets server state.
     *
     * @param playerId player requesting to quit the game
     */
    public void quitGame(String playerId){
        System.out.println("[SERVER_APP] quitGame called by: " + playerId);

        MessageToClient message = controller.quitGame(playerId);
        MessageToClient messageToLobby = new QuitLobbyMessage("One or more players has requested to exit, you're disconnected",true);

        message.deliver(playerId, this);
        messageToLobby.deliver(null,this);

        System.out.println("[SERVER_APP] Quit broadcast completed.");

        resetServer();
    }

    /**
     * Handles a voluntary lobby quit and removes the client associated with the session.
     *
     * @param sessionId lobby session identifier to disconnect
     */
    public void quitLobby(String sessionId){

        MessageToClient message = new QuitLobbyMessage("Ti sei disconnesso dalla lobby",false);
        message.deliver(sessionId, this);

        unregisterLobbyClient(sessionId);

    }
    /**
     * Clears game and lobby network registries, closes known client endpoints, and resets heartbeat state.
     */
    private void resetServer(){
        synchronized (gameClients) {
            for (VirtualView gameClient : gameClients.values()) {
                try {
                    gameClient.close();
                } catch (Exception ignored) {
                }
            }

            gameClients.clear();
            System.out.println("[SERVER_APP] Game client map cleared " + gameClients);
        }

        synchronized (lobbyClients) {
            for (VirtualView lobbyClient : lobbyClients.values()) {
                try {
                    lobbyClient.close();
                } catch (Exception ignored) {
                }
            }

            lobbyClients.clear();
            System.out.println("[SERVER_APP] Lobby client map cleared " + lobbyClients);
        }
        stopAliveChecker();
        synchronized (lastPingByClient) {
            lastPingByClient.clear();
            System.out.println("[SERVER_APP] Ping map cleared " + lastPingByClient);
        }
        if(isGameCrashed.get()) isGameCrashed.set(false);
    }

    /**
     * Updates the heartbeat timestamp for a client and sends a pong response.
     *
     * @param sender client endpoint that sent the ping command
     * @throws Exception if the pong response cannot be delivered
     */
    public void ping(VirtualView sender) throws Exception {
        if (sender == null) {
            return;
        }

        synchronized (lastPingByClient) {
            lastPingByClient.put(sender, System.currentTimeMillis());
        }

        pong(sender);
    }

    /**
     * Sends a pong response to either a game client or a lobby client.
     *
     * @param sender client endpoint that sent the ping
     * @throws Exception if the client identifier cannot be read or the message cannot be delivered
     */
    private void pong(VirtualView sender) throws Exception {
        synchronized (gameClients) {
            String playerId = sender.getPlayerId();

            if (playerId != null && gameClients.containsKey(playerId)) {
                sendTo(playerId, new PongMessage());
                System.out.println("[SERVER_APP] PongMessage game client " + playerId);
                return;
            }
        }

        synchronized (lobbyClients) {
            for (Map.Entry<String, VirtualView> entry : lobbyClients.entrySet()) {
                if (entry.getValue().equals(sender)) {
                    sendToSession(entry.getKey(), new PongMessage());
                    System.out.println("[SERVER_APP] PongMessage lobby client "
                            + sender.getClass().getSimpleName());
                    return;
                }
            }
        }
    }

    /**
     * Starts the server-side heartbeat checker if it is not already running.
     */
    private void startAliveChecker() {
        if (aliveCheckerStarted) {
            return;
        }

        aliveCheckerStarted = true;

        aliveChecker.schedule(new TimerTask() {
            /**
             * Detects clients that have stopped sending pings and schedules disconnection handling.
             */
            @Override
            public void run() {
                try {
                    List<VirtualView> disconnectedClients = checkPingTimeouts();

                    if (!disconnectedClients.isEmpty()) {
                        System.out.println("[SERVER_APP] Timed-out clients: "
                                + disconnectedClients.size());

                        List<VirtualView> snapshot = List.copyOf(disconnectedClients);
                        disconnectionExecutor.submit(() -> handleClientDisconnection(snapshot));
                    }

                } catch (Exception e) {
                    System.out.println("[PING] Error alive checker: " + e.getMessage());
                }
            }
        }, 0, 1500);

        System.out.println("[PING] Alive checker started");
    }

    /**
     * Stops the current heartbeat checker and creates a new timer for future sessions.
     */
    private void stopAliveChecker() {
        try {
            aliveChecker.cancel();
        } catch (Exception ignored) {}

        aliveChecker = new Timer(true);
        aliveCheckerStarted = false;

        System.out.println("[PING] Alive checker stopped");
    }

    /**
     * Finds clients whose latest ping is older than the configured timeout.
     * <p>
     * Timed-out clients are removed immediately from the ping map to prevent the
     * timer from scheduling the same disconnection repeatedly before it is processed.
     *
     * @return client endpoints considered disconnected
     */
    private List<VirtualView> checkPingTimeouts() {
        List<VirtualView> disconnectedClients = new ArrayList<>();
        long now = System.currentTimeMillis();

        synchronized (lastPingByClient) {
            if(!lastPingByClient.isEmpty()){
                var iterator = lastPingByClient.entrySet().iterator();

                while (iterator.hasNext()) {
                    Map.Entry<VirtualView, Long> entry = iterator.next();

                    VirtualView client = entry.getKey();
                    long lastPing = entry.getValue();
                    long elapsed = now - lastPing;

                    if (elapsed > PING_TIMEOUT_MS) {
                        disconnectedClients.add(client);
                        iterator.remove();
                    }
                }
            }
        }
        return disconnectedClients;
    }


    /**
     * Handles clients detected as disconnected by the heartbeat checker.
     * <p>
     * A game-client disconnection crashes the active game, notifies remaining clients,
     * disconnects lobby clients, and resets the server. A lobby-only disconnection
     * only removes that lobby session.
     *
     * @param disconnectedClients disconnected client endpoints detected by timeout
     */
    private void handleClientDisconnection(List<VirtualView> disconnectedClients) {
        if (disconnectedClients == null || disconnectedClients.isEmpty()) {
            return;
        }
        List<String> disconnectedPlayersId = new ArrayList<>();
        List<String> sessionDisconnectedIds = new ArrayList<>();

        synchronized (gameClients) {
            for (Map.Entry<String, VirtualView> entry : gameClients.entrySet()) {
                if (disconnectedClients.contains(entry.getValue())) {
                    disconnectedPlayersId.add(entry.getKey());
                }
            }
        }
        synchronized (lobbyClients) {
            for (Map.Entry<String, VirtualView> entry : lobbyClients.entrySet()) {
                if (disconnectedClients.contains(entry.getValue())) {
                    sessionDisconnectedIds.add(entry.getKey());
                }
            }
        }
        if (!disconnectedPlayersId.isEmpty()) {
            System.out.println("[SERVER_APP] Disconnected game clients: " + disconnectedPlayersId);

            synchronized (gameClients) {
                for (String id : disconnectedPlayersId) {
                    gameClients.remove(id);
                }
            }

            synchronized (lobbyClients) {
                for (String sid : sessionDisconnectedIds) {
                    lobbyClients.remove(sid);
                }
            }

            for (VirtualView crashed : disconnectedClients) {
                try {
                    crashed.close();
                } catch (Exception ignored) {}
            }

            if (!this.isGameCrashed.get()) {
                MessageToClient message;
                synchronized (gameLock) {
                    message = controller.handleGameCrashed();
                }

                if (message != null) {
                    this.isGameCrashed.set(true);
                    message.deliver(null, this);
                    MessageToClient messageToLobby = new QuitLobbyMessage("Uno o più giocatori hanno chiesto di uscire dal game, sarai disconnesso...",true);
                    messageToLobby.deliver(null, this);
                }
            }
            resetServer();
            return;
        }

        if (!sessionDisconnectedIds.isEmpty()) {
            System.out.println("[SERVER_APP] Disconnected lobby clients: " + sessionDisconnectedIds);

            synchronized (lobbyClients) {
                for (String sid : sessionDisconnectedIds) {
                    lobbyClients.remove(sid);
                }
            }
            synchronized (lastPingByClient) {
                System.out.println("[SERVER_APP] Disconnected clients in lastPingByClient: " + lastPingByClient);
                if(lastPingByClient.isEmpty()) {
                    stopAliveChecker();
                }
            }
            for (VirtualView client : disconnectedClients) {
                try {
                    client.close();
                } catch (Exception ignored) {}
            }
        }
    }

    /**
     * Broadcasts the latest lobby snapshot to clients that are still waiting in the lobby.
     */
    private void broadcastLobbyStatus() {
        MessageToClient lobbyMessage =
                new LobbyStatusMessage(controller.getLobbyView(), "Lobby aggiornata.");

        broadcastToLobby(lobbyMessage);
    }

    /**
     * Sends a message to a single lobby client identified by its temporary session id.
     *
     * @param sessionId lobby session identifier
     * @param message   message to deliver
     */
    @Override
    public void sendToSession(String sessionId, MessageToClient message) {
        VirtualView client;

        synchronized (lobbyClients) {
            client = lobbyClients.get(sessionId);
        }

        if (client == null) {
            System.out.println("[SERVER_APP] ERROR: lobby session not found: " + sessionId);
            return;
        }

        try {
            client.onMessage(message);
        } catch (Exception e) {
            System.out.println("[SERVER_APP] Lobby client unreachable: " + sessionId
                    + ", error: " + e.getMessage());
        }
    }

    /**
     * Broadcasts a message to all clients currently registered in the lobby.
     *
     * @param message message to deliver to lobby clients
     */
    @Override
    public void broadcastToLobby(MessageToClient message) {
        Map<String, VirtualView> copy;

        synchronized (lobbyClients) {
            copy = new HashMap<>(lobbyClients);
        }

        for (Map.Entry<String, VirtualView> entry : copy.entrySet()) {
            String sessionId = entry.getKey();
            VirtualView client = entry.getValue();

            try {
                client.onMessage(message);
            } catch (Exception e) {
                System.out.println("[SERVER_APP] Lobby client unreachable during broadcast: "
                        + sessionId
                        + ", error: "
                        + e.getMessage());

            }
        }
    }

    /**
     * Sends a message to one player already registered in the active game.
     *
     * @param playerId player identifier used to locate the client endpoint
     * @param message  message to deliver
     */
    @Override
    public void sendTo(String playerId, MessageToClient message) {
        VirtualView client;

        synchronized (gameClients) {
            client = gameClients.get(playerId);
        }

        System.out.println("[SERVER_APP] sendTo "
                + message.getClass().getSimpleName()
                + " to: "
                + playerId);

        if (client == null) {
            System.out.println("[SERVER_APP] ERROR: client not found: " + playerId);
            return;
        }

        try {
            client.onMessage(message);

            System.out.println("[SERVER_APP] sendTo completed for: " + playerId);

        } catch (Exception e) {
            System.out.println("[SERVER_APP] Client " + playerId
                    + " unreachable in sendTo: "
                    + e.getMessage());

//            synchronized (gameClients) {
//                if (gameClients.get(playerId) == client) {
//                    gameClients.remove(playerId);
//                }
//            }
//
//            synchronized (lastPingByClient) {
//                lastPingByClient.remove(client);
//            }
//
//            try {
//                client.close();
//            } catch (Exception ignored) {
//            }
        }
    }

    /**
     * Broadcasts a message to every client registered in the active game.
     *
     * @param message message to deliver to game clients
     */
    @Override
    public void broadcast(MessageToClient message) {
        Map<String, VirtualView> copy;

        synchronized (gameClients) {
            copy = new HashMap<>(gameClients);
        }

        System.out.println("[SERVER_APP] broadcast "
                + message.getClass().getSimpleName()
                + " to clients: "
                + copy.keySet());

        for (Map.Entry<String, VirtualView> entry : copy.entrySet()) {
            String playerId = entry.getKey();
            VirtualView client = entry.getValue();

            try {
                System.out.println("[SERVER_APP] Sending broadcast to: " + playerId);

                client.onMessage(message);

                System.out.println("[SERVER_APP] Broadcast completed for: " + playerId);

            } catch (Exception e) {
                System.out.println("[SERVER_APP] Client " + playerId
                        + " unreachable during broadcast ");

            }
        }
    }

}